# Generated by Django 4.2.17 on 2024-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.URLField(default="www.google.com"),
        ),
    ]
