# Generated by Django 4.2.17 on 2025-01-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="description",
            field=models.CharField(default="No Description Provided", max_length=500),
        ),
    ]
